apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
  labels:
    app: producer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
      - name: producer-service
        image: ayedk/producer-service:latest
        ports:
        - containerPort: 8080