apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.streamApi.name }}
  labels:
    app: {{ .Values.streamApi.labels.app }}
spec:
  type: {{ .Values.streamApi.service.type }}
  ports:
    - port: {{ .Values.streamApi.service.port }}
      targetPort: {{ .Values.streamApi.service.targetPort }}
      protocol: TCP
      name: jmx
  selector:
    app:  {{ .Values.streamApi.name }}