
server.port: 5656
# queues configs
downstream.connection.out.queue: downstream_out_queue
downstream.connection.in.queue: downstream_in_queue

upstream.connection.out.queue: upstream_out_queue
upstream.connection.in.queue: upstream_in_queue



# producer config
producer.bootstrap-servers: kafka:9092

# consumer configs
consumer.bootstrap-servers: kafka:9092
downstream.consumer.group-id: notif-group
upstream.consumer.group-id: bid-group
consumer.auto-offset-reset: latest