# Default values for auction-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## ------------------------------------------------------
## Stream Api
## ------------------------------------------------------
streamApi:
  name: stream-api
  labels:
    app: stream-api

  replicaCount: 1
  spec:
    name: stream-api
    image:
      repository:  ayedk/stream-api
      pullPolicy: IfNotPresent
      tag:  "latest"

    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    
    volumeMounts:
      name: config
      mountPath:  stream-api/config
      readOnly: true

  configMap:
    name: stream-api-configs
    key:  app-configs
    path: application.properties

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50


## ------------------------------------------------------
## Up Stream
## ------------------------------------------------------
upstream:
  name: upstream
  labels:
    app: upstream
    

  replicaCount: 1
  spec:
    name: upstream
    image:
      repository:  ayedk/upstream
      pullPolicy: IfNotPresent
      tag:  "latest"
    
    ports:
      containerPort:  8080

  service:
    type: ClusterIP
    port: 8080

## ------------------------------------------------------
## Down Stream
## ------------------------------------------------------
downstream:
  name: down-stream
  labels:
    app: down-stream


  replicaCount: 1
  spec:
    name: down-stream
    image:
      repository:  ayedk/down-stream
      pullPolicy: IfNotPresent
      tag:  "latest"

## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
kafka:
  name: kafka
  labels:
    app: kafka


  replicaCount: 1
  spec:
    name: kafka
    image:
      repository:  wurstmeister/kafka
      pullPolicy: IfNotPresent
      tag:  "latest"
    
    ports:
      containerPort:  5656
    
    volumeMounts:
      name: data
      mountPath:  /kafka

  
  volumeClaimTemplates:
    name: data
    accessModes: "ReadWriteOnce"
    storageClassName: standard
    storage:  5Gi
  
  configMap:
    name: kafka-config
  
  headless:
    clusterIP:  None
    port: 9092
    targetPort: 9092

  service:
    type: ClusterIP
    port: 9092
    targetPort: 9092


## ------------------------------------------------------
## Mysql
## ------------------------------------------------------
mysql:
  name: mysql
  labels:
    app: mysql

  
  replicaCount: 1
  spec:
    name: mysql
    image:
      repository:  mysql
      pullPolicy: IfNotPresent
      tag:  "latest"
    
    ports:
      containerPort:  3306
    
    volumeMounts:
      name: data
      mountPath:  "/var/lib/mysql"


  volumeClaimTemplates:
    name: data
    accessModes: "ReadWriteOnce"
    storageClassName: standard
    storage:  5Gi

  secret:
    name: mysql-secret

  service:
    type: ClusterIP
    port: 3306

## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
zookeeper:
  name: zookeeper
  labels:
    app: zookeeper

  replicaCount: 1
  spec:
    name: zookeeper
    image:
      repository:  zookeeper
      pullPolicy: IfNotPresent
      tag:  "latest"
    
    ports:
      zkclient:
        containerPort:  2181
      zkfollower:
        containerPort:  2888
      zkelection:
        containerPort:  3888
    
    volumeMounts:
      - name: data
        mountPath:  /data
      - name: log
        mountPath:  /datalog

  volumeClaimTemplates:
    data:
      name: data
      accessModes: "ReadWriteOnce"
      storageClassName: standard
      storage:  1Gi
    log:
      name: log
      accessModes: "ReadWriteOnce"
      storageClassName: standard
      storage:  1Gi

  configMap:
    name: zk-config

  headless:
    clusterIP:  None

    election:
      port: 3888
      targetPort: 3888

    follower:
      port: 2888
      targetPort: 2888
    

  service:
    type: ClusterIP
    port: 2181
    targetPort: 2181

## ------------------------------------------------------
## Back Up
## ------------------------------------------------------
backup:
  namespace: kube-system
  name: backup
  # you can switch enabled to false if you want to disable backup
  enabled: true
  schedule: "*/1 * * * *"

  spec:
    image:
      repository:  k8s.gcr.io/etcd
      pullPolicy: IfNotPresent
      tag:  "3.4.13-0"
    
    volumeMounts:
      - name: etcd-certs
        mountPath:  /etc/kubernetes/pki/etcd
        readOnly: true
      - name: backup
        mountPath: /backup
    
    volumes:
    - name: etcd-certs
      hostPath:
        path: /var/lib/minikube/certs/etcd
        type: DirectoryOrCreate
    - name: backup
      hostPath:
        path: /c/Users/e5640132/Desktop/backup
        type: DirectoryOrCreate
