apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  ports:
  - name: client
    protocol: TCP
    port: 2181
    targetPort: 2181
  selector:
    app: zookeeper