apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-headless
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: follower
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: election 
      protocol: TCP
      port: 3888
      targetPort: 3888
  selector:
    app: zookeeper