apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: broker-headless
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: client
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: zookeeper