apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
  labels:
    app: broker
spec:
  serviceName: broker-headless
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: wurstmeister/kafka:latest
        imagePullPolicy: Always
        ports:
        - name: client
          containerPort: 9092
          protocol: TCP
        env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: broker-0.broker-headless
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
        volumeMounts:
        - name: broker-data
          mountPath: /kafka
  volumeClaimTemplates:
  - metadata:
      name: broker-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
