apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.kafka.name }}
  labels:
    app: {{ .Values.kafka.labels.app }}
spec:
  serviceName: {{ .Values.kafka.name }}-headless
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.labels.app }}
    spec:
      containers:
      - name: {{ .Values.kafka.spec.name }}
        image: "{{ .Values.kafka.spec.image.repository }}:{{ .Values.kafka.spec.image.tag }}"
        imagePullPolicy: {{ .Values.kafka.spec.image.pullPolicy }}
        ports:
        - name: client
          containerPort: {{ .Values.kafka.spec.ports.containerPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.kafka.configMap.name }}
        volumeMounts:
        - name: {{ .Values.kafka.spec.volumeMounts.name }}
          mountPath: {{ .Values.kafka.spec.volumeMounts.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.kafka.volumeClaimTemplates.name }}
    spec:
      accessModes: ["{{ .Values.kafka.volumeClaimTemplates.accessModes }}"]
      storageClassName: {{ .Values.kafka.volumeClaimTemplates.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.kafka.volumeClaimTemplates.storage }}
