apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.downstream.name }}
  labels:
    app: {{ .Values.downstream.labels.app }}
  annotations:
    "helm.sh/hook-weight": "{{ .Values.downstream.annotations.order }}"
spec:
  replicas: {{ .Values.downstream.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.downstream.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.downstream.labels.app }}
    spec:
      containers:
      - name: {{ .Values.downstream.spec.name }}
        image: "{{ .Values.downstream.spec.image.repository }}:{{ .Values.downstream.spec.image.tag }}"
        imagePullPolicy: {{ .Values.downstream.spec.image.pullPolicy }}